import subprocess
import os
import shutil


def execute_dangerzone(filename):
    # remove existing dest safe file
    fn_rm = '/root/dangerzone/safe_output/'+filename+'.pdf'
    if os.path.isfile(fn_rm):
        os.remove(fn_rm)

    # remove existing pixel file
    filelist = []
    mydir_pixel = '/root/dangerzone/dangerzone-pixel'
    for f in os.listdir(mydir_pixel):
        if f.endswith(".height") or f.endswith(".rgb") or f.endswith(".width"):
            filelist.append(f)
    for f in filelist:
        os.remove(os.path.join(mydir_pixel, f))

    # remove existing /tmp safe file
    filelist = []
    mydir_safe = '/root/dangerzone/dangerzone-safe'
    for f in os.listdir(mydir_safe):
        if f.endswith(".pdf"):
            filelist.append(f)
    for f in filelist:
        os.remove(os.path.join(mydir_safe, f))

    # convert file to image pdf
    uploadpath = '/root/dangerzone/' + filename
    filename_split = uploadpath.split('.')
    possible_format = "pdf docx doc xlsx xls pptx ppt odt ods odp odg jpg jpeg gif png tif tiff hwp"

    if filename_split[-1] in possible_format:
        # hwp to xhtml, xhtml to pdf
        if filename_split[-1] == 'hwp':

            # remove pdf generated by whktml
            htmldir_path = "/root/dangerzone/wkhtmltopdf"
            if filename[:-4] + ".pdf" in os.listdir(htmldir_path):
                os.remove(htmldir_path + "/" + filename[:-4] + ".pdf")

            # convert hwp to xhtml, generate filename directory
            subprocess.call(["/root/.local/bin/hwp5html " + uploadpath], shell=True)
            # convert to pdf
            subprocess.call(["xvfb-run /usr/bin/wkhtmltopdf " + os.getcwd() + "/" + filename[:-4] + "/index.xhtml " + htmldir_path + "/" + filename[:-4] + ".pdf"], shell=True)
            uploadpath = htmldir_path + "/" + filename[:-4] + ".pdf"

            # remove .local/bin/filename
            dir_local_bin = os.getcwd() + "/" + filename[:-4]
            if os.path.isdir(dir_local_bin):
                shutil.rmtree(dir_local_bin)

        subprocess.call([
            "/usr/bin/dangerzone-container" " documenttopixels --document-filename " + uploadpath + " --pixel-dir /root/dangerzone/dangerzone-pixel --container-name flmcode/dangerzone"],
            shell=True)
        subprocess.call([
            "/usr/bin/dangerzone-container" " pixelstopdf --pixel-dir /root/dangerzone/dangerzone-pixel --safe-dir /root/dangerzone/dangerzone-safe --container-name flmcode/dangerzone --ocr 0 --ocr-lang eng"],
            shell=True)
    else:
        this = filename_split[-1]
        print(f"can't convert '{this}' type")
        return

    # copy to dest
    path = '/root/dangerzone/safe_output/'
    file_url = '/root/dangerzone/dangerzone-safe/safe-output-compressed.pdf'
    dest_url = path + filename[:-4] + ".pdf"
    try:
        shutil.move(file_url, dest_url)
    except:
        print("The file to be moved does not exist\n")


if __name__ == '__main__':
    execute_dangerzone('example.hwp')
