# Generated by Django 3.1.3 on 2021-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='md5',
            field=models.TextField(default=''),
        ),
    ]
